language: ruby
rvm:
  - 2.1.1
sudo: false
script:
  - bundle exec jekyll build
  # can't get htmlproofer to run with {{ site.baseurl }}
  #- bundle exec htmlproofer ./_site --only-4xx --check-html --allow-hash-href --disable-external
after_success:
  - bash gh-pages.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
